### PR TITLE
Update dtprcs2.s

### PR DESCRIPTION
**Pull request by TheAmazingSui**
Added MRS instruction

### CODE REVIEW

**Comment by TheAmazingSui** [comment]
plz plz plz plz approve

**Comment by TheAmazingSui** [comment]
I need money to live plz

**Comment by pepp3rrr** [comment]
your code sucks

**Comment by pepp3rrr** [comment]
chocolate peanut butter

**Comment by pepp3rrr** [comment]
it broke duc code

**Review by DoDucAnh2810 — CHANGES_REQUESTED** [review]
Remove the mrs test pls

**Comment by TheAmazingSui** [comment]
what a scam

**Comment by pepp3rrr** [comment]
get outta here kid

**Comment by TheAmazingSui** [comment]
LEETSS  GOOOO

**Pull request merged**
